apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: projet-final
  labels:
    app: backend
spec:
  # Type ClusterIP (Par défaut) car ce service ne doit pas être exposé à l'extérieur
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
