apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: projet-final
  labels:
    app: frontend
spec:
  # NodePort pour rendre l'interface accessible de l'extérieur
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      # Port statique imposé
      nodePort: 30080
      protocol: TCP
